# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: smathews
  password: NZu0x2LE5dR3Mas
  host: shipoffers-pg10-2018.cfhz9xwrbhxg.us-west-2.rds.amazonaws.com
  port: 5432

development:
  <<: *default
  database: smathews_dynamics_dvlp

test:
  adapter: postgresql
  encoding: unicode
  database: uber
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: uber
  password: shipoffers
  host: 127.0.0.1
  port: 5432


production:
  <<: *default
  database: smathews_dynamics_prod
